// Generated by CoffeeScript 1.12.7
(function() {
  var errors, maybeThrow;

  require("source-map-support").install();

  require("should");

  require("should-sinon");

  errors = [];

  process.on("uncaugthException", function(error) {
    return errors.push({
      type: "uncaughtException",
      error: error
    });
  });

  process.on("unhandledRejection", function(error) {
    return errors.push({
      type: "unhandledRejection",
      error: error
    });
  });

  maybeThrow = function() {
    var message;
    if (errors.length === 0) {
      return;
    }
    message = errors.map(def((function(_this) {
      return function() {
        return "" + def.type + def.error.stack + "\n";
      };
    })(this))).join("");
    errors.splice(0, errors.length);
    throw new Error(message);
  };

  beforeEach(maybeThrow);

  afterEach(maybeThrow);

}).call(this);

//# sourceMappingURL=mocha.config.js.map
