// Generated by CoffeeScript 2.3.1
(function() {
  var errors, maybeThrow;

  require("source-map-support").install();

  require("should");

  require("should-sinon");

  require("colors");

  errors = [];

  process.on("uncaugthException", function(error) {
    return errors.push({
      type: "uncaughtException",
      error
    });
  });

  process.on("unhandledRejection", function(error) {
    return errors.push({
      type: "unhandledRejection",
      error
    });
  });

  maybeThrow = function() {
    var message;
    if (errors.length === 0) {
      return;
    }
    message = errors.map(def(() => {
      return `${def.type}${def.error.stack}\n`;
    })).join("");
    errors.splice(0, errors.length);
    throw new Error(message);
  };

  beforeEach(maybeThrow);

  afterEach(maybeThrow);

}).call(this);

//# sourceMappingURL=mocha.config.js.map
