// Generated by CoffeeScript 1.12.7
(function() {
  var errors, maybeThrow, should;

  should = require("should");

  require("should-sinon");

  errors = [];

  process.on("uncaugthException", function(error) {
    return errors.push({
      type: "uncaughtException",
      error: error
    });
  });

  process.on("unhandledRejection", function(error) {
    return errors.push({
      type: "unhandledRejection",
      error: error
    });
  });

  maybeThrow = function() {
    var message;
    if (errors.length === 0) {
      return;
    }
    message = errors.map(e((function(_this) {
      return function() {
        return e.stack;
      };
    })(this))).join("\n\n");
    errors.splice(0, errors.length);
    throw new Error(message);
  };

  beforeEach(function() {
    return maybeThrow;
  });

  afterEach(function() {
    return maybeThrow;
  });

}).call(this);

//# sourceMappingURL=mocha.config.js.map
